### ISSUE TITLE
New-bConnectEndpoint: Allow operationg system installation

### ISSUE THREAD

**Issue by nydeggerm** [baramundisoftware/PS-bConnect#10]
Please expand the command "New-bConnectEndpoint" with "Allow operating systems installation"

**Comment by T0biii** [comment]
You need to set the "Options" Parameter to "1"
Like: `New-bConnectEndpoint -Type WindowsEndpoint -DisplayName "Test1" -GroupGuid $guid -Options 1`
Options of an endpoint (see coding baramundi bConnect 1.1 Doku Page 71)

**Comment by nydeggerm** [comment]
Works great. Thanks a lot for your fast response.

Was on Page 70 ("[Options] 0x00000001 Admits an OS installation")
Maybe you can Change the text there to "Allow operating systems installation" (Which is the Name of the Checkbox in the bMC). It would be easier to find.

**Comment by T0biii** [comment]
Nope i can't change the Text :P  but maybe @baramundi-ahaugk can do it.

**Comment by baramundi-ahaugk** [comment]
I have forwarded your request to the team.
