### ISSUE TITLE
two new examples

### ISSUE THREAD

**Issue by nydeggerm** [baramundisoftware/PS-bConnect#11]
Nachfolgend zwei Vorschläge für neue Beispiele:

Credentials in einer Datei speichern: https://stackoverflow.com/a/6240319/8364227

```
# Vorgaengig muss folgender Befehl ausgefuehrt werden: read-host -assecurestring | convertfrom-securestring | out-file .\bconnect_securestring_for_powershell.txt

$bconnectusername = "bconnect"
$bconnectpassword = Get-Content '.\bconnect_securestring_for_powershell.txt' | ConvertTo-SecureString

$bconnectapiCred = new-object -typename System.Management.Automation.PSCredential -argumentlist $bconnectusername, $bconnectpassword

# Verbindung aufbauen
Initialize-bConnect -Server "1.2.3.4" -Credentials $bconnectapiCred -AcceptSelfSignedCertifcate
```

-------------------------------------------------------------------

Vorschlag für ein neues Beispiel "CreateNewEndpointInSubgroup.ps1"
```
# Search parent group
$bconnectidofparentorg = Search-bConnectorgunit "Servers"

# Define Name of new group
$bconnectGroupname = "Serversubroup"

# Create new sub group
New-bConnectOrgUnit -Name $bconnectGroupname -ParentGuid $bconnectidofparentorg.Id


# Search GroupID
$bconnectidoforg = Search-bConnectorgunit $bconnectGroupname

# Create New Endpoint
New-bConnectEndpoint -Type WindowsEndpoint -DisplayName "bcTest" -HostName "bcTest" -PrimaryMac "AA-BB-CC-DD-EE-FF" -GroupGuid $bconnectidoforg.Id
```

**Comment by T0biii** [comment]
Kannst gerne ein Pull request dafür aufmachen :)

**Comment by T0biii** [comment]
Bein zweiten Vorschlag könnte man sich das zweite suchen sparen wenn man "New-bConnectOrgUnit" in eine Variable "speichert" weil dort solle man die ID von der neuen OrgUnit schon zurück bekommen haben. Des weiteren wird ja dann immer ein Endpoint erstellt und eine SupGroup?

**Comment by nydeggerm** [comment]
> Kannst gerne ein Pull request dafür aufmachen :)
Ich bin nicht so bewandert im github, weshalb ich nachforschen müsste, wie das geht. -.-

> Bein zweiten Vorschlag könnte man sich das zweite suchen sparen wenn man "New-bConnectOrgUnit" in eine Variable "speichert" weil dort solle man die ID von der neuen OrgUnit schon zurück bekommen haben. Des weiteren wird ja dann immer ein Endpoint erstellt und eine SupGroup?

Ja, das ist korrekt. Danke für den Hinweis. In meinem Fall hatte ich noch eine Subgroup erstellt.
Das wäre noch der Code nur mit einem neuen Client in einer bestimmten Gruppe


"CreateNewEndpointInSubgroup.ps1"
```
# Search GroupID
$bconnectidoforg = Search-bConnectorgunit "Servers"

# Create New Endpoint
New-bConnectEndpoint -Type WindowsEndpoint -DisplayName "bcTest" -HostName "bcTest" -PrimaryMac "AA-BB-CC-DD-EE-FF" -GroupGuid $bconnectidoforg.Id
```

**Comment by T0biii** [comment]
So? oder wollen wir noch was ändern?
"CreateNewEndpointInSubgroup.ps1"
```Powershell
# Import Module
Import-Module -Name bConnect
# Get Crediential
$apiCred = Get-Credential -Message "bConnect" -UserName "user@domain.local"
# Initialize bConnect Module
Initialize-bConnect -Server "SRV-BARAMUNDI" -Credentials $apiCred
# Search GroupID
$orgUnit = Search-bConnectorgunit "Servers"
# Create New Endpoint in the 
New-bConnectEndpoint -Type WindowsEndpoint -DisplayName "bcTest" -HostName "bcTest" -PrimaryMac "AA-BB-CC-DD-EE-FF" -GroupGuid $orgUnit.Id

```

**Comment by nydeggerm** [comment]
Danke dafür. Ich habe lediglich noch Ergänzungen in den Kommentaren, um das Verständnis zu steigern.

`> # Search GroupID for the group "Servers". Name of the group (search string "Servers") must be unique in the group structure.`

`> # Create New Endpoint in Group "Servers" ($orgUnit.Id)`




Hier noch das Beispiel, dass auf https://github.com/baramundisoftware/PS-bConnect im Abschnitt "Usage" ergänzt werden könnte. Was meinst du dazu?

```
# Import Module
Import-Module -Name bConnect

# Before the lines below works the command on the next line must be run once (ask for password for user "user@domain.local" and save it to file "bconnect_securestring.txt").
# Run in Powershell: read-host -assecurestring | convertfrom-securestring | out-file .\bconnect_securestring.txt

$username = "user@domain.local"
$password = Get-Content '.\bconnect_securestring.txt' | ConvertTo-SecureString

$apiCred = new-object -typename System.Management.Automation.PSCredential -argumentlist $username, $password

# Initialize connection
Initialize-bConnect -Server "SRV-BARAMUNDI" -Credentials $apiCred
```

**Comment by baramundi-ahaugk** [comment]
Eine Funktion zum Speichern der Credentials ist absichtlich nicht Teil des Moduls, da das über die Funktion des reinen Wrappers hinaus geht.
Die Verwaltung von Anmeldeinformationen ist ein heikles Thema und sollte generell (und scriptübergreifend) z.B. mit einem eigenen Modul gelöst werden, welches dann in allen PS-Projekten - auch losgelöst von bConnect - verwendet werden kann.
Zudem ist die Nutzung von SecureString einigen Einschränkungen unterworfen: https://docs.microsoft.com/de-de/dotnet/api/system.security.securestring?view=netframework-4.8#HowSecure
