### ISSUE TITLE
New-bConnectStaticGroup.ps1 funktioniert nicht

### ISSUE THREAD

**Issue by T0biii** [baramundisoftware/PS-bConnect#12]
Ich glaube die Funktion "[New-bConnectStaticGroup](https://github.com/baramundisoftware/PS-bConnect/blob/master/bConnect/Public/New-bConnectStaticGroup.ps1
)" funktioniert garnicht?
Oben will er den Paramter Endpoints aber weiter unten wird der Paramter Statement initialisiert und Endpoints überhaupt nicht. 
Und wenn ich den Befehl ausführe  wird nur eine leere Statische Gruppe erstellt. Egal was man dem Paramter Statement mit gibt

**Comment by baramundi-ahaugk** [comment]
DU hast Recht, sieht mir nach Copy & Paste vom DynGroupController aus. Ich korrigiere das sobald möglich.

**Comment by T0biii** [comment]
Hiermit geschließe ich das Issue siehe: dacffc2a5c873983d41867aebf88a9004b0fa5ec und 42ec05e1f63d2c2d2b73e70f4b7a364b906276a4
Dachte es ist noch garnicht gelöst sieht aber nun gelöst aus. 
FYI: @baramundi-skrusbersky in der Commit message hättest du "fix #12" oder [ähnliches](https://docs.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords) verwenden können dann wäre das Issue automatisch geschlossen worden wenn der Commit in den master gepusht wird
