### ISSUE TITLE
Test-Guid in Edit-bConnectApplication?

### ISSUE THREAD

**Issue by T0biii** [baramundisoftware/PS-bConnect#16]
Gibt es einen Grund das in allen Edit-*.ps1 Dateien Test-Guid gemacht wird nur in [Edit-bConnectApplication](https://github.com/baramundisoftware/PS-bConnect/blob/master/bConnect/Public/Edit-bConnectApplication.ps1) nicht?
Ist mir aufgefallen durch #15

**Comment by baramundi-ahaugk** [comment]
Das ist mir tatsächlich durchgerutscht. Selbstverständlich sollte auch hier ein Test-Guid stattfinden. Werde ich anpassen.

**Comment by BeneSchm** [comment]
Wenn ich versuche den Befehl "Edit-bConnectEndpoint" aufzurufen und nachfolgend als $Endpoint die GUID angebe, kommt der Fehler
`Test-Guid : Cannot bind argument to parameter 'Guid' because it is an empty string.`
Mache ich etwas falsch?
Grüße

**Comment by baramundi-lkersten** [comment]
dort muss nicht die GUID des Endpoints angegeben werden sondern der komplette Endpoint als PS-Objekt 

$EP = get-bconnectEndpoint -EndpointGuid $Endpoint_ID
Edit-bConnectEndpoint -Endpoint $EP

**Comment by BeneSchm** [comment]
Ah okay, vielen Dank für die schnelle und ausführliche Antwort!
