### ISSUE TITLE
`get-bConnectSoftwareScanRule` returns empty/no rules

### ISSUE THREAD

**Issue by rjaeckel** [baramundisoftware/PS-bConnect#25]
When using the `SoftwareScanRule` API-Endpoint the property `Rules` of each returned dataset remains empty. This is probably a problem that resides on the server side.

```
get-bConnectSoftwareScanRule |? IsMswRule -ne True |? Rules -ne @()
```

The `Rules` property is marked as _deprecated_ in documentation, but there's actually no way to get or modify the actual rules that match at registry or file level.

**Comment by baramundi-lkersten** [comment]
that's correct 
the `Rules` are no longer transmitted by the bServer 
Since it is not a problem in the module itself I close the issue

as soon as the appropriate information is returned by the server we can take up this topic again
