### ISSUE TITLE
WARNUNG: NOT SUPPORTED! Unknown bConnect Version -> Fallback to v1.0

### ISSUE THREAD

**Issue by thericosanto** [baramundisoftware/PS-bConnect#27]
Ich setze das aktuelle bConnect Modul 20.1.0.1 aus der Powershell Gallery ein und bekomme bei jedem Befehl den ich absetze den Hinweis, dass ein Fallback durchgeführt wird, obwohl unser Baramundi Server die Version 1.1 bereits unterstützt.
Beim Abfragen mit Get-bconnectInfo wird folgendes ausgegeben:

Description     : Interface to baramundi Management Server
Company         : baramundi software AG
Copyright       : Copyright (C) baramundi software AG 2020
bConnectVersion : 1.1
bMSVersion      : 20.1.203.0
UserContext     : admin-XXXX@XXXXXX.de

Ich setze die Powershell 5.1 in 64bit auf einem Windows 10 Rechner ein. 
Unser Baramundiserver wurde vor 2 Wochen auf die Version 2020 aktualisiert.
Ich selbst bin ein Junior Powershell Wizard.

Sollten weitere Infos nötig sein, gerne melden. :)

**Comment by T0biii** [comment]
Die neuste Version des Modules wurde nun bei [Powershellgallery](https://www.powershellgallery.com/packages/bConnect/20.1.0.2) veröffentlicht (20.1.0.2)
Einmal bitte `Update-Module -Name bConnect` durchführen

Issue kann somit geschlossen werden.
