### ISSUE TITLE
New-bConnectEndpoint Parameter -PrimaryMAC wird nicht übergeben

### ISSUE THREAD

**Issue by szg-mw** [baramundisoftware/PS-bConnect#34]
**Describe the bug**

New-bConnectEndpoint -... -PrimaryMAC "11:11:11:11:11:11"

Der Endpoint wird entsprechend in Baramundi angelegt, jedoch wird die MAC-Adresse nicht angelegt.
Der Bug konnte bereits von den Kollegen von Baramundi bestätigt werden. Ticketnummer (#222246)

**To Reproduce**
Command wie oben beschrieben mit den notwendigen Parametern absetzten.

| My operating system | Server 2019 |
| baramundi Server Version | 2020R1 |
| PS-bConnect Version | 19.2.0.5 |

**Aktueller Workaround**
Endpoints über New-bConnectEndpoint anlegen und dann über Edit-bConnectApplication bearbeiten.

**Comment by T0biii** [comment]
Kurze Frage "Bug konnte bereits von den Kollegen von Baramundi" also ist es eher ein bConnect auf dem Server Fehler und kein Module Fehler?

**Comment by szg-mw** [comment]
Hallo,

sollte bedeuten, dass der Fehler im PS-Modul liegt und die Kollegen von Baramundi den Fehler auch entsprechend nachstellen konnten.

**Comment by T0biii** [comment]
@szg-mw gerne um sicher zugehen das es nicht an der Modul Version liegt einmal auf die "neuste" Version Updaten [(20.1.0.3)](https://www.powershellgallery.com/packages/bConnect/20.1.0.3)

**Comment by T0biii** [comment]
Dein Fehler ist bereits gefixt: 6355da5dc7daedc7bab3d1917bc029f250fcecd8
Aber es wurde anscheinend noch nicht in der PS Gallery geupdatet. 
@baramundi-ahaugk

**Comment by szg-mw** [comment]
Hi,

habe eben noch die aktuelle Version installiert und auf case sensitivity geachtet, Fehler ist aber immer noch da

**Comment by T0biii** [comment]
Hast du sie manuell installiert? Weil die neuste Version ist nich nicht Verfügbar

**Comment by szg-mw** [comment]
Nevermind, hab das gerade auch gemerkt, als ich die Version nochmal geprüft habe.

**Comment by baramundi-ahaugk** [comment]
Version 20.1.0.4 mit dem Fix ist nun in der PS Gallery
