### ISSUE TITLE
Edit-bConnectEndpoint UserCategory

### ISSUE THREAD

**Issue by T0biii** [baramundisoftware/PS-bConnect#38]
saw this Report in the Forum:
https://forum.baramundi.de/index.php?threads/edit-bconnectendpoint-funktioniert-nicht.10758/#post-52619

**Comment by baramundi-ahaugk** [comment]
fixed
https://github.com/baramundisoftware/PS-bConnect/commit/9311c94a74d44db2a4e7b691ed5b3894da3e69f0#diff-35cc2a83ce6f7b6d55e060e912306175d80c2299d9aaa07c29ee224806410bdf
