### ISSUE TITLE
bConnect install agent

### ISSUE THREAD

**Issue by SKHRO** [baramundisoftware/PS-bConnect#40]
Hello, unfortunately I can not find a way to install the agent via bConnect. Am I just blind or does this not exist?

**Comment by T0biii** [comment]
Hey @SKHRO,

I think you're right because I haven't found a controller for this yet either.
And the Endpoints Controller also has no option for this (maybe to get this in bConnect you need to create an Idea in the [Feedback Portal](http://feedback.baramundi.de/) for it)

**Comment by baramundi-ahaugk** [comment]
It's not nesseccary to install the agent by command.
If configured properly the server will install/upgrade the agent as soon as an active job is assigned/started on an endpoint.
