### ISSUE TITLE
Enable Run AD Sync with bConnect

### ISSUE THREAD

**Issue by SKHRO** [baramundisoftware/PS-bConnect#41]
I would like to run the AD Sync process through the CMDLETs. Is this function already possible?

**Comment by T0biii** [comment]
Hey @SKHRO,

I haven't found a controller for this.
Maybe to get this in bConnect you need to create an Idea in the [Feedback Portal](http://feedback.baramundi.de/)  for it

**Comment by baramundi-lkersten** [comment]
Hello All,

thank you SKHRO for creating as idea in baramundi feedback portal 
so I close this issue
