### ISSUE TITLE
Update bConnect

### ISSUE THREAD

**Issue by SKHRO** [baramundisoftware/PS-bConnect#49]
Hallo, 
bekomme seit 2021 R1 Fehlermeldungen das die bConnect Version nicht passt.
Laut Baramundi Support soll ich hier eine aktuelle Version anfordern.

Vielen Dank

Michael Hochmuth

**Comment by T0biii** [comment]
Hey Michael,

im Repo hier liegt bereits die angepasste Version die diese Fehlermeldung behebt. 
Nur wurde diese von Baramundi noch nicht in der PSGallary hochgeladen.

**Comment by SKHRO** [comment]
Hallo T0biii,

in welchem Repository meinst du?
Aktuell habe ich in der Powershell Module Version 20.1.0.5 (wie auch hier angezeigt) Damit bekomme ich aber immer noch die Fehlermeldung.

**Comment by T0biii** [comment]
Die Versionsnummer in dem Repository wurde noch nicht hochgezählt die Änderung hier für ist aber bereits gemacht worden siehe: https://github.com/baramundisoftware/PS-bConnect/commit/73ec23f7fb30c730068c600050d11f27f9b1c9bb
Seit dem wurde aber keine neue Version in die PSGallary hochgeladen.
Du kannst theoretisch die betroffene Datei hier runterladen: "[bConnect/Private/Get-bConnectVersion.ps1](https://github.com/baramundisoftware/PS-bConnect/blob/master/bConnect/Private/Get-bConnectVersion.ps1)" und sie ersetzen. Dennoch wäre es schöner wenn Baramundi das Module selbst noch updaten würde in der PSGallary.
Wie es bereits in #48 auch bereits schon einmal gefordert wurde.

**Comment by T0biii** [comment]
this can be closed the [PowerShell Gallery](https://www.powershellgallery.com/packages/bConnect/21.1.0.0) is uptodate
