### ISSUE TITLE
Get-bConnectDynamicGroup -UniversalDynamicGroup

### ISSUE THREAD

**Issue by duczz** [baramundisoftware/PS-bConnect#50]
Seit der 2020 R2 gibt die "Get-bConnectDynamicGroup -UniversalDynamicGroup" leider ist das Command im Modul noch nicht enthalten

**Comment by T0biii** [comment]
Glaube dies sollte auch ein eigener Befehl werden da es ein eigener Controller ist.
Damit man sich Endpoints über die UniversalDynmaicGroupID holen kann gibt es bereits einen offenen Pull request #47
