### ISSUE TITLE
Die zugrunde liegende Verbindung wurde geschlossen: Unerwarteter Fehler beim Senden..

### ISSUE THREAD

**Issue by duczz** [baramundisoftware/PS-bConnect#52]
Ich erhalte immer folgenden Fehler, jemand eine Idee woran das liegt?

`Invoke-bConnectGet : Die zugrunde liegende Verbindung wurde geschlossen: Unerwarteter Fehler beim Senden..
In C:\Program Files\WindowsPowerShell\Modules\bConnect\Public\Get-bConnectInfo.ps1:9 Zeichen:33
+ ... ript:_bConnectInfo = Invoke-bConnectGet -Controller "info" -noVersion
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-bConnectGet
 
Invoke-bConnectGet : Die zugrunde liegende Verbindung wurde geschlossen: Unerwarteter Fehler beim Senden..
In C:\Program Files\WindowsPowerShell\Modules\bConnect\Public\Get-bConnectInfo.ps1:9 Zeichen:33
+ ... ript:_bConnectInfo = Invoke-bConnectGet -Controller "info" -noVersion
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-bConnectGet`

**Comment by duczz** [comment]
hmm, scheint sich erledigt zu haben nachdem man alle Powershells geschlossen hat und neu probiert.

**Comment by T0biii** [comment]
> hmm, scheint sich erledigt zu haben nachdem man alle Powershells geschlossen hat und neu probiert.

hm klingt komisch aber wenn es jetzt geht umso besser.
Schließt du das Issue dann selber?
