### ISSUE TITLE
Typo in Option -AcceptSelfSignedCertificate in Initialize-bConnect

### ISSUE THREAD

**Issue by Scancee** [baramundisoftware/PS-bConnect#65]
Initialize-bConnect has a Typo in option to accept selfsigned certificates.

Expected option:
-AcceptSelfSignedCertificate

Actual option:
-AcceptSelfSignedCertifcate ( missing second i in certificate )

**Comment by baramundi-ahaugk** [comment]
Already fixed, see #44
