### ISSUE TITLE
Search-bConnectEndpoint returns $true if no matches were found

### ISSUE THREAD

**Issue by uka-support** [baramundisoftware/PS-bConnect#66]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/baramundisoftware/PS-bConnect/issues).

**Describe the bug**
When searching for an endpoint and there are no results, the function returns $true instead of $null

**To Reproduce**
```
$result = Search-bConnectEndpoint -Term "no-such-endpoint"
if ($result) { 
   # try to use the result
}
```

**Expected behavior**
It should return $null if there were no matches.

**System information**
| Question | Answer |
| --- | --- |
| My operating system | Server 2016|
| baramundi Server Version | 2021R2 |
| PS-bConnect Version | 21.1.0.0|

**Additional context**

**Comment by baramundi-ahaugk** [comment]
Technically all search functions work correct - they do not return $true.
If you perform a search by manually calling the search controller i.e. via browser, you'll get an empty "SearchResult" array, which will be transported directly into your script. There is no mechnic implemented to match an empty result to $null.
If you want to work with the result, try "foreach" to iterate through the result.

**Comment by maetz3** [comment]
I faced the same problem, especially if you want to process the variable further.
For example, in the following example, every GUID that exists in the database is output.

$Endpoint = Search-bConnectEndpoint -Term "no-such-endpoint"
$Endpoint = Get-bConnectEndpoint -EndpointGuid $Endpoint.id

My solution was to customize the function:
Line 23+: 
$SearchResult = Invoke-bConnectGet -Controller "Search" -Version $_connectVersion -Data $_body
if($SearchResult.Id) {
	return $SearchResult
} else {
	$false
}
