### ISSUE TITLE
add NetworkEndpoint to New/Edit-bConnectEndpoint 

### ISSUE THREAD

**Issue by T0biii** [baramundisoftware/PS-bConnect#74]
add NetworkEndpoint to [New-bConnectEndpoint](https://github.com/baramundisoftware/PS-bConnect/blob/master/bConnect/Public/New-bConnectEndpoint.ps1) and [Edit-bConnectEndpoint](https://github.com/baramundisoftware/PS-bConnect/blob/master/bConnect/Public/Edit-bConnectEndpoint.ps1)

**Comment by scheppachbde** [comment]
Hello,

I tried to add a new networkEndpoint with new-bconnectendpoint but I always receive "PrimaryIP must not be empty"
my command was "New-bConnectEndpoint -Type NetworkEndpoint -DisplayName dr0000 -PrimaryIP 10.10.10.10", so I added a primaryIP.

should that feature already work and it is a bug on my side, or is that feature not ready yet?

**Comment by T0biii** [comment]
this issue is a feature request to add support for it. (There is also an Error in the bServer: https://forum.baramundi.com/index.php?threads/networkendpoints-21r2.13602/) 

If you want to try it you need to add some lines to the new-bconnectEndpoint.ps1
See: https://gist.github.com/T0biii/c565069628c2e3a43973882207abf995#file-new-bconnectendpoint-ps1-L51-L58

**Comment by scheppachbde** [comment]
very cool, it works for me. thanks for your help
