### ISSUE TITLE
Get DIP Status

### ISSUE THREAD

**Issue by hellgelino** [baramundisoftware/PS-bConnect#75]
Wir benötigen eine Abfrage zur Ermittlung der DIP Stati.

**Comment by baramundi-ahaugk** [comment]
Das Modul ist nur ein Wrapper für die bestehende Funktionalität der bConnect-Schnittstelle. Der Status der DIPs kann aktuell noch nicht über bConnect abgefragt werden, daher kann auch das Modul diese Funktion nicht bieten.

---

The module is only a wrapper for the existing functionality of the bConnect interface. The status of the DIPs can currently not be queried via bConnect, therefore the module can also not offer this function.
