### ISSUE TITLE
AD-SYNC

### ISSUE THREAD

**Issue by hellgelino** [baramundisoftware/PS-bConnect#76]
Wir benötigen eine Möglichkeit zur selektiven Synchronization des ADs auf Basis:

Ziel AD -> OU Angabe

**Comment by baramundi-ahaugk** [comment]
Das Modul ist nur ein Wrapper für die bestehende Funktionalität der bConnect-Schnittstelle. Die gewünschte Funktion ist im AD-Sync nicht enthalten und damit auch nicht per Schnittstelle verfügbar.

---

The module is only a wrapper for the existing functionality of the bConnect interface. The desired function is not included in AD-Sync and therefore not available via interface.
