### ISSUE TITLE
FR: Get specific data from given Endpoints (Bitlocker PIN, Serial Number, etc.)

### ISSUE THREAD

**Issue by noshdvar** [baramundisoftware/PS-bConnect#77]
Hi,

i have read the possible Commands, and it seems that there is no such possibility to get an output of the used Bitlocker PIN for a specific device. I could as well be wrong :)

My use case would be:
- a custom Script to automatically write out some Documents for Users.

For this i would like to get out the following data:
- used Bitlocker PIN to unlock the device
- device name

For other documents (delivery notices) i would also like to get the following data from baramundi:
- Serial number
- Manufacturer
- and the Model Name

Is there a way to achieve this?
thank you in advance!

**Comment by T0biii** [comment]
Does this two commands help you?
[Get-bConnectEndpoint](https://github.com/baramundisoftware/PS-bConnect/blob/master/bConnect/Public/Get-bConnectEndpoint.ps1)
[Get-bConnectEndpointSecret](https://github.com/baramundisoftware/PS-bConnect/blob/master/bConnect/Public/Get-bConnectEndpointSecret.ps1)

**Comment by noshdvar** [comment]
Thank you, i will try them in the following days and will get back to you!

**Comment by T0biii** [comment]
@noshdvar i tried the commands on my instance and got all necessary informations.
so do you need some more help?
