### ISSUE TITLE
WARNING: UNSUPPORTED bMS Version 23.1.172.0! Unknown bConnect Version -> Fallback to v1.0

### ISSUE THREAD

**Issue by hellgelino** [baramundisoftware/PS-bConnect#84]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/baramundisoftware/PS-bConnect/issues).

**Describe the bug**
WARNING: UNSUPPORTED bMS Version 23.1.172.0! Unknown bConnect Version -> Fallback to v1.0

**System information**
| Question | Answer |
| --- | --- |
| baramundi Server Version | 2023R1 |
| PS-bConnect Version | 21.1.0.0 |

**Additional context**

**Comment by T0biii** [comment]
you can fix it by editing this file:
https://github.com/baramundisoftware/PS-bConnect/blob/master/bConnect/Private/Get-bConnectVersion.ps1

**Comment by NorbertPU** [comment]
Dear Tobias,

thank you for the quick response.
Editing Get-bConnectVersion.ps1 fixed the problem.

Thank you
Norbert
