### ISSUE TITLE
Add LocalID + Architecture to Create new Endpoint as parameters

### ISSUE THREAD

**Issue by phillscholl** [baramundisoftware/PS-bConnect#85]
Please add **LocalID** and **Architecture** as a parameter to the **New-bConnectEndpoint**.

Example: New-bConnectEndpoint -Type WindowsEndpoint -DisplayName "$hostname" -HostName "$hostname" -LocalID 1033 -Architecture "x64"

**Comment by T0biii** [comment]
i guess this two informations are collectet via mini Inventur. 
in the Docs this to Properties are read Only:
![image](https://github.com/baramundisoftware/PS-bConnect/assets/5702338/b871f5dc-a5f7-4b90-b3a2-f46ea459eca8)
![image](https://github.com/baramundisoftware/PS-bConnect/assets/5702338/16aa73ee-9c59-4b76-ba46-494b4de0e030)
so it cant be set via bConnect

**Comment by phillscholl** [comment]
Then why can i set them when i create an endpoint in baramundi?:
![image](https://github.com/baramundisoftware/PS-bConnect/assets/150017878/566d9b11-878f-4077-a24d-58bae91ca05f)

**Comment by T0biii** [comment]
good question maybe someone from Baramundi can answer it:
@baramundi-ahaugk
@baramundi-lkersten  
or open a ticket

**Comment by baramundi-ahaugk** [comment]
This script only utilizes the existing functions of the bConncet API. The requested properties are read-only.

You may open a feature request via [Feedback-Portal](https://feedback.baramundi.de/) to request a change in the future.
